title: Hans5958's Mini HTMLs
email: ""
description: Ready or not, here we go! Website of Hans5958.
baseurl: /mini-htmls
url: https://hans5958.github.io

author: Hans5958
twitter: "@Hans5958"
copyright_year: 2021
repository: https://github.com/Hans5958/mini-htmls

markdown: kramdown
exclude: ["README.md", "CODE_OF_CONDUCT.md"]
livereload: true

source: site
