title: Hans5958's Mini HTMLs
email: ""
description: Ready or not, here we go! Website of Hans5958.
baseurl: /mini-htmls
url: https://hans5958.github.io

author: Hans5958
twitter: "@Hans5958"
copyright_year: 2021
repository: https://github.com/Hans5958/mini-htmls

source: site
markdown: kramdown
livereload: false

plugins:
  - jekyll-sitemap
  - jekyll-default-layout
  - jekyll-minifier
  - jekyll-autoprefixer
  - jekyll-git_metadata

autoprefixer:
  browsers:
  - ">= 1%"
  - last 1 major version
  - not dead
  - Chrome >= 60
  - Firefox >= 60
  - Edge >= 16
  - iOS >= 10
  - Safari >= 10
  - Android >= 6
  - not Explorer <= 11

jekyll-minifier:
  exclude: 
    - "**/*.html"
  uglifier_args:
    harmony: true
